// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdc6PUGIHR9DZ07n_KTJrlQJgFxE8TzVk',
    appId: '1:121076303829:web:1d0a4f15704e9067375f5c',
    messagingSenderId: '121076303829',
    projectId: 'travelchat-a8df5',
    authDomain: 'travelchat-a8df5.firebaseapp.com',
    storageBucket: 'travelchat-a8df5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5apqBqXrxw32yxBB7kUZYRLOVjr07Ua4',
    appId: '1:121076303829:android:35e148e7243f44ad375f5c',
    messagingSenderId: '121076303829',
    projectId: 'travelchat-a8df5',
    storageBucket: 'travelchat-a8df5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ--Zc8Ebusmcc7CcHwEKAeq6FDAc2S_E',
    appId: '1:121076303829:ios:ba28af3d5f50ea55375f5c',
    messagingSenderId: '121076303829',
    projectId: 'travelchat-a8df5',
    storageBucket: 'travelchat-a8df5.appspot.com',
    iosBundleId: 'com.example.travelchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ--Zc8Ebusmcc7CcHwEKAeq6FDAc2S_E',
    appId: '1:121076303829:ios:be59e896f3374e2c375f5c',
    messagingSenderId: '121076303829',
    projectId: 'travelchat-a8df5',
    storageBucket: 'travelchat-a8df5.appspot.com',
    iosBundleId: 'com.example.travelchat.RunnerTests',
  );
}
